// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vera.Data;

#nullable disable

namespace Vera.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Vera.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FreelancerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHourly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 85000m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Şirketimiz için özelleştirilmiş ERP yazılımı geliştirilmesi. Muhasebe, stok yönetimi ve insan kaynakları modülleri olacak.",
                            EmployerId = 4,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Kurumsal ERP Sistemi"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 450m,
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Satış verilerinin analizi, görselleştirilmesi ve makine öğrenmesi ile tahminleme modeli oluşturulması.",
                            EmployerId = 4,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "Python ile Veri Analizi"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 300m,
                            CreatedAt = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kurumsal sitemizin Google sıralamasını yükseltme. Teknik SEO, içerik stratejisi ve backlink çalışması yapılacak.",
                            EmployerId = 4,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "SEO Optimizasyonu"
                        },
                        new
                        {
                            Id = 4,
                            Budget = 12000m,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eğitim amaçlı platform oyunu. Fizik motorları, karakter animasyonları ve level design dahil.",
                            EmployerId = 4,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Unity 2D Oyun Geliştirme"
                        },
                        new
                        {
                            Id = 5,
                            Budget = 550m,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yavaş sorguların iyileştirilmesi, index stratejisi ve veritabanı normalizasyonu.",
                            EmployerId = 4,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "PostgreSQL DB Optimizasyonu"
                        },
                        new
                        {
                            Id = 6,
                            Budget = 750m,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Müşteri hizmetleri için OpenAI API kullanarak akıllı chatbot geliştirilmesi ve web sitesine entegrasyonu.",
                            EmployerId = 4,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "AI Chatbot Entegrasyonu"
                        },
                        new
                        {
                            Id = 7,
                            Budget = 3000m,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Firma tanıtım videoları için profesyonel hareketli logo animasyonu tasarlanması.",
                            EmployerId = 4,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Logo Animasyonu (After Effects)"
                        },
                        new
                        {
                            Id = 8,
                            Budget = 2500m,
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yeni e-ticaret markamız için minimalist, modern ve akılda kalıcı logo tasarımı.",
                            EmployerId = 5,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "E-Ticaret Logo Tasarımı"
                        },
                        new
                        {
                            Id = 9,
                            Budget = 150m,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknoloji ve yazılım üzerine haftalık 5 SEO uyumlu blog içeriği üretilmesi.",
                            EmployerId = 5,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "Blog İçerik Yazarlığı"
                        },
                        new
                        {
                            Id = 10,
                            Budget = 5000m,
                            CreatedAt = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ana sayfa, ürün detay ve sepet sayfalarının modern trendlere göre yeniden tasarlanması.",
                            EmployerId = 5,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Figma UI/UX Revizesi"
                        },
                        new
                        {
                            Id = 11,
                            Budget = 200m,
                            CreatedAt = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "15 dakikalık vlog içerikleri için profesyonel kurgu, renk düzeltme ve efektler.",
                            EmployerId = 5,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "Video Kurgu (YouTube)"
                        },
                        new
                        {
                            Id = 12,
                            Budget = 18000m,
                            CreatedAt = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "API entegreli sosyal medya yönetim paneli. Instagram, Twitter ve TikTok desteği olacak.",
                            EmployerId = 5,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "SMM Panel Yazılımı"
                        },
                        new
                        {
                            Id = 13,
                            Budget = 1500m,
                            CreatedAt = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "30 adet özel vektörel ikon. Hem iOS hem Android uyumlu SVG formatında.",
                            EmployerId = 5,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Mobil Tasarım İkon Seti"
                        },
                        new
                        {
                            Id = 14,
                            Budget = 120m,
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknik yazılım dokümantasyonu çevirisi. 50 sayfa, terminolojiye hakim biri aranıyor.",
                            EmployerId = 5,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "İngilizce-Türkçe Çeviri"
                        },
                        new
                        {
                            Id = 15,
                            Budget = 35000m,
                            CreatedAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gerçek zamanlı teslimat takibi, harita entegrasyonu ve push notification desteği olan mobil uygulama.",
                            EmployerId = 6,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "React Native Kurye Uygulaması"
                        },
                        new
                        {
                            Id = 16,
                            Budget = 600m,
                            CreatedAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mevcut monolitik API'lerin mikroservis mimarisine geçirilmesi ve Docker container'larına taşınması.",
                            EmployerId = 6,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "Dockerize Microservices"
                        },
                        new
                        {
                            Id = 17,
                            Budget = 3500m,
                            CreatedAt = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Liquid kodları ile özel bölümler ekleme, ürün filtreleme ve mega menü geliştirme.",
                            EmployerId = 6,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Shopify Tema Düzenleme"
                        },
                        new
                        {
                            Id = 18,
                            Budget = 20000m,
                            CreatedAt = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Web sitesi ve API'ler için kapsamlı sızma testi, güvenlik açığı taraması ve detaylı raporlama.",
                            EmployerId = 6,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Cyber Security Audit"
                        },
                        new
                        {
                            Id = 19,
                            Budget = 4000m,
                            CreatedAt = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Özel tema geliştirme, WooCommerce entegrasyonu ve çok dilli destek.",
                            EmployerId = 6,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "WordPress Kurumsal Site"
                        },
                        new
                        {
                            Id = 20,
                            Budget = 400m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mevcut Flutter projesindeki performans sorunları ve bug'ların temizlenmesi.",
                            EmployerId = 6,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "Flutter Hata Giderme"
                        },
                        new
                        {
                            Id = 21,
                            Budget = 6000m,
                            CreatedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ubuntu sunucularda güvenlik sıkılaştırma, firewall konfigürasyonu ve SSH güvenliği.",
                            EmployerId = 6,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Linux Server Hardening"
                        },
                        new
                        {
                            Id = 22,
                            Budget = 500m,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ürün arama altyapısı için Elasticsearch cluster kurulumu ve veri indeksleme.",
                            EmployerId = 4,
                            IsHourly = true,
                            Status = "Açık",
                            Title = "Elasticsearch Kurulumu"
                        },
                        new
                        {
                            Id = 23,
                            Budget = 8000m,
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Satış ve finans verilerinin Power BI ile görselleştirilmesi ve otomatik raporlama.",
                            EmployerId = 5,
                            IsHourly = false,
                            Status = "Açık",
                            Title = "Power BI Dashboard"
                        });
                });

            modelBuilder.Entity("Vera.Models.ProjectStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProjectStages");
                });

            modelBuilder.Entity("Vera.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "10 yıllık deneyimli backend geliştirici. ASP.NET Core, Entity Framework, SQL Server ve mikroservis mimarileri konusunda uzmanım. Temiz kod yazarım, deadline'lara uyarım.",
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emin@vera.com",
                            FullName = "Emin Sancaklı",
                            Password = "AQAAAAIAAYagAAAAELggRWGw0Y5I3Qz4nqcZrX+yrTnAkRpu40a3YShF3ehPI55Ql/if1x79o5TavR+bTg==",
                            Role = "Freelancer",
                            Skills = "C#,.NET Core,Entity Framework,SQL Server,Docker,REST API",
                            Title = "Senior .NET Developer",
                            WalletBalance = 45000m
                        },
                        new
                        {
                            Id = 2,
                            About = "Figma, Adobe XD ve Illustrator ile kullanıcı deneyimi odaklı tasarımlar yapıyorum. Minimalist ve modern arayüzler benim tutkum.",
                            CreatedAt = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse@vera.com",
                            FullName = "Ayşe Demir",
                            Password = "AQAAAAIAAYagAAAAEFO22SnDn9nTgM2/bi1t5L7ClLM43Qoq7+LaE6qbz9p/sLVTawy/iP2UMsAStzYiRg==",
                            Role = "Freelancer",
                            Skills = "Figma,Adobe XD,Illustrator,Photoshop,UI/UX,Wireframing",
                            Title = "UI/UX & Marka Tasarımcısı",
                            WalletBalance = 28000m
                        },
                        new
                        {
                            Id = 3,
                            About = "React, Next.js, Node.js ve MongoDB ile modern web uygulamaları geliştiriyorum. 7 yıllık sektör deneyimim var.",
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mehmet@vera.com",
                            FullName = "Mehmet Kaya",
                            Password = "AQAAAAIAAYagAAAAEMW5P74VHokV9plAI/YTo4zW+ygGHoPeP/xxOdZF7PG8/ShcRtpw4djlXMQ8nfp9bw==",
                            Role = "Freelancer",
                            Skills = "React,Next.js,Node.js,MongoDB,TypeScript,GraphQL",
                            Title = "Full Stack Developer (React & Node.js)",
                            WalletBalance = 62000m
                        },
                        new
                        {
                            Id = 7,
                            About = "Flutter ve Dart ile cross-platform mobil uygulamalar geliştiriyorum. Firebase, REST API entegrasyonları ve state management konularında deneyimliyim.",
                            CreatedAt = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zeynep@vera.com",
                            FullName = "Zeynep Yıldız",
                            Password = "AQAAAAIAAYagAAAAEJAa1y+XAvkSwxhDGuOG5d0yavwv4esglLAKKIpRQJs3nOqrTXNne70qUPCXm/9XeQ==",
                            Role = "Freelancer",
                            Skills = "Flutter,Dart,Firebase,REST API,iOS,Android",
                            Title = "Mobil Uygulama Geliştirici (Flutter)",
                            WalletBalance = 15500m
                        },
                        new
                        {
                            Id = 8,
                            About = "AWS, Azure, Docker, Kubernetes ve CI/CD pipeline'ları konusunda uzmanım. Altyapı optimizasyonu ve sunucu yönetimi yapıyorum.",
                            CreatedAt = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "can@vera.com",
                            FullName = "Can Özturk",
                            Password = "AQAAAAIAAYagAAAAEDUWyPtxgzZt6HGZMvqB1o0rThVNvKnpdLx5Quy2Ohyjgi5nYwBgABzrS9pQ3cjnwQ==",
                            Role = "Freelancer",
                            Skills = "AWS,Azure,Docker,Kubernetes,CI/CD,Linux",
                            Title = "DevOps & Cloud Mühendisi",
                            WalletBalance = 38000m
                        },
                        new
                        {
                            Id = 4,
                            About = "Kurumsal yazılım çözümleri ve dijital dönüşüm hizmetleri sunuyoruz.",
                            CreatedAt = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@zirve.com",
                            FullName = "Zirve Teknoloji A.Ş.",
                            Password = "AQAAAAIAAYagAAAAEHVCsnUxinidhJESKxAoISYv7S5d+n6O4Om91Xh40tKDiA1W2ev7jBACgHsjcq7wJA==",
                            Role = "Employer",
                            Title = "Yazılım Ajansı",
                            WalletBalance = 100000m
                        },
                        new
                        {
                            Id = 5,
                            About = "Yaratıcı tasarım, sosyal medya yönetimi ve marka stratejisi alanında lider ajans.",
                            CreatedAt = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@pixel.com",
                            FullName = "Pixel Medya",
                            Password = "AQAAAAIAAYagAAAAEO4DC/d4UENc52xjzvMVF4ncFaxD/SDONaUVBxKCLIkClx9Gukk5GHbyxaDmQYoYOg==",
                            Role = "Employer",
                            Title = "Dijital Ajans",
                            WalletBalance = 80000m
                        },
                        new
                        {
                            Id = 6,
                            About = "Türkiye genelinde lojistik ve dağıtım hizmetleri sunan köklü bir firma.",
                            CreatedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@global.com",
                            FullName = "Global Lojistik",
                            Password = "AQAAAAIAAYagAAAAECwT89g/mqcSGzG+14LIGyZ97cfOHGb+/7HFN6dP0EvqTcE7avqS9ucfuM8Fe+uJIg==",
                            Role = "Employer",
                            Title = "Lojistik & Dağıtım",
                            WalletBalance = 250000m
                        });
                });

            modelBuilder.Entity("Vera.Models.WorkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Hours")
                        .HasColumnType("REAL");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("Vera.Models.WorkLog", b =>
                {
                    b.HasOne("Vera.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
