// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vera.Data;

#nullable disable

namespace Vera.Migrations.LogDb
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20260510174911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Vera.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Yeni Teklif Kabul Edildi",
                            Details = "Kurumsal ERP Sistemi projesi için teklifiniz Zirve Teknoloji tarafından onaylandı.",
                            Timestamp = new DateTime(2026, 5, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Hesaba Geçti",
                            Details = "₺12.500 tutarındaki hakedişiniz bakiyenize başarıyla eklendi.",
                            Timestamp = new DateTime(2026, 5, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Action = "Sistem Güncellemesi",
                            Details = "Vera v2.0 yayında! Yeni özellikleri hemen keşfedin.",
                            Timestamp = new DateTime(2026, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Action = "Yeni Proje Eşleşmesi",
                            Details = "Yeteneklerinize uygun 'Mobil Uygulama Tasarımı' projesi yayınlandı.",
                            Timestamp = new DateTime(2026, 5, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Action = "Yeni İş İlanı Yayınlandı",
                            Details = "React Native Kurye Uygulaması projesi yayına alındı.",
                            Timestamp = new DateTime(2026, 5, 4, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            Action = "Ödeme Yapıldı",
                            Details = "Figma UI/UX Revizesi projesi için freelancer'a ₺5.000 ödeme yapıldı.",
                            Timestamp = new DateTime(2026, 5, 7, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Vera.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Emin Bey selamlar, ERP projesi için yarın Zoom üzerinden bir toplantı yapabilir miyiz?",
                            IsRead = false,
                            ReceiverId = 1,
                            SenderId = 4,
                            SentAt = new DateTime(2026, 5, 9, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Harika olur, yarın saat 14:00 benim için çok uygun. Linki iletebilirsiniz.",
                            IsRead = true,
                            ReceiverId = 4,
                            SenderId = 1,
                            SentAt = new DateTime(2026, 5, 9, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Ayşe Hanım, renk paleti harika olmuş! Alt sayfa tasarımlarına da başlayabiliriz.",
                            IsRead = true,
                            ReceiverId = 2,
                            SenderId = 5,
                            SentAt = new DateTime(2026, 5, 8, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Content = "API dokümantasyonunu inceledik, çok temiz bir iş çıkarmışsınız. Sözleşme için hukuk departmanımız size dönüş yapacak.",
                            IsRead = false,
                            ReceiverId = 1,
                            SenderId = 6,
                            SentAt = new DateTime(2026, 5, 9, 16, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Mehmet Bey, backend API'yi ne zaman teslim edebilirsiniz?",
                            IsRead = true,
                            ReceiverId = 3,
                            SenderId = 4,
                            SentAt = new DateTime(2026, 5, 8, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Perşembe gününe kadar ilk sürümü hazırlayabilirim.",
                            IsRead = true,
                            ReceiverId = 4,
                            SenderId = 3,
                            SentAt = new DateTime(2026, 5, 8, 10, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Content = "Zeynep Hanım, Flutter uygulama mockup'larını gördük, harika görünüyor!",
                            IsRead = false,
                            ReceiverId = 7,
                            SenderId = 5,
                            SentAt = new DateTime(2026, 5, 7, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
